apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-cluster.fullname" . }}
  labels: {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  selector: {{- include "kafka-cluster.labels" . | nindent 4 }}
  ports:
  - port: 9093
    targetPort: 9093
    name: server
    nodePort: 32093
  type: NodePort