apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-cluster.fullname" . }}-headless
  labels: {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  selector: {{- include "kafka-cluster.labels" . | nindent 4 }}
  clusterIP: None
  ports:
  - name: server
    port: 9093
    