kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ include "kafka-signle.fullname" . }}
  labels: {{- include "kafka-signle.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "kafka-signle.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels: {{- include "kafka-signle.labels" . | nindent 8 }}
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: {{ include "kafka-signle.fullname" . }}
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster:2181
        - name: KAFKA_BROKER_ID
          value: "1"