apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper-cluster.fullname" . }}
  labels: {{- include "zookeeper-cluster.labels" . | nindent 4 }}
spec:
  selector: {{- include "zookeeper-cluster.labels" . | nindent 4 }}
  ports:
  - name: client
    port: {{ .Values.image.port }}
    targetPort: {{ .Values.image.port }}
    nodePort: {{ .Values.image.nodePort }}
  type: NodePort