apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper-cluster.fullname" . }}-headless
  labels: {{- include "zookeeper-cluster.labels" . | nindent 4 }}
spec:
  selector: {{- include "zookeeper-cluster.labels" . | nindent 4 }}
  clusterIP: None
  ports:
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  publishNotReadyAddresses: true