apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper-cluster.fullname" . }}
  labels: {{- include "zookeeper-cluster.labels" . | nindent 4 }}
spec:
  selector: {{- include "zookeeper-cluster.labels" . | nindent 4 }}
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 32181
  type: NodePort