# Default values for mysql-panshi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  mainPort: 3306
  nodePort: 32306
  repository: mysql
  tag: "8.0"
  env:
    - name: MYSQL_ROOT_PASSWORD
      value: 123qwe@

imagePullSecrets: []
