apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-demo.fullname" . }}
  labels:
    {{- include "helm-demo.labels" . | nindent 4 }}
spec:
  ports:
  - name: main-port
    port: {{ .Values.image.mainPort }}
    protocol: TCP
    targetPort: {{ .Values.image.mainPort }}
  selector:
    {{- include "helm-demo.labels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP